export default async function Home() {
  return (
    <main className="p-8 md:p-10 lg:grid lg:grid-cols-12">
      <div className="typo-heading-1 space-y-5 text-neutral-100 md:space-y-10 lg:col-span-8 [&>p]:whitespace-pre-line">
        <p>
          WHEN A GROUP OF FRIENDS WITH VARIED EXPERTISE GATHERED OVER A BOTTLE OF WINE, THE VAL COMPANY LIMITED WAS
          BORN.
        </p>
        <p>
          WITH ONLY 14 RESIDENCES, EXPERIENCE THE EXCLUSIVITY AND PRIVACY THAT BLEND WITH NATURE TO CREATE A HARMONIOUS
          BALANCE BETWEEN SOLITUDE AND CONNECTION WITH FAMILY AND COMMUNITY
        </p>
        <p>HERE, OUR GOAL IS TO SHARE A SPACE OF SUSTAINABLE, TIMELESS QUALITY FOR LIVING</p>
        <p>
          WHEN A GROUP OF FRIENDS WITH VARIED EXPERTISE GATHERED OVER A BOTTLE OF WINE, THE VAL COMPANY LIMITED WAS
          BORN.
        </p>
        <p>
          WITH ONLY 14 RESIDENCES, EXPERIENCE THE EXCLUSIVITY AND PRIVACY THAT BLEND WITH NATURE TO CREATE A HARMONIOUS
          BALANCE BETWEEN SOLITUDE AND CONNECTION WITH FAMILY AND COMMUNITY
        </p>
        <p>HERE, OUR GOAL IS TO SHARE A SPACE OF SUSTAINABLE, TIMELESS QUALITY FOR LIVING</p>
        <p>
          WHEN A GROUP OF FRIENDS WITH VARIED EXPERTISE GATHERED OVER A BOTTLE OF WINE, THE VAL COMPANY LIMITED WAS
          BORN.
        </p>
        <p>
          WITH ONLY 14 RESIDENCES, EXPERIENCE THE EXCLUSIVITY AND PRIVACY THAT BLEND WITH NATURE TO CREATE A HARMONIOUS
          BALANCE BETWEEN SOLITUDE AND CONNECTION WITH FAMILY AND COMMUNITY
        </p>
        <p>HERE, OUR GOAL IS TO SHARE A SPACE OF SUSTAINABLE, TIMELESS QUALITY FOR LIVING</p>
        <p>
          WHEN A GROUP OF FRIENDS WITH VARIED EXPERTISE GATHERED OVER A BOTTLE OF WINE, THE VAL COMPANY LIMITED WAS
          BORN.
        </p>
        <p>
          WITH ONLY 14 RESIDENCES, EXPERIENCE THE EXCLUSIVITY AND PRIVACY THAT BLEND WITH NATURE TO CREATE A HARMONIOUS
          BALANCE BETWEEN SOLITUDE AND CONNECTION WITH FAMILY AND COMMUNITY
        </p>
        <p>HERE, OUR GOAL IS TO SHARE A SPACE OF SUSTAINABLE, TIMELESS QUALITY FOR LIVING</p>
      </div>
    </main>
  )
}
